name: Deploy backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/Portfolio
            git pull origin main
            cd backend
            npm ci
            pm2 restart portfolio-backend